version: "3.9"  # optional since v1.27.0
services:
    db:
        build: ./environment/company_db
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=pass
    server_a: 
        build: ./environment/user_server_a
        ports:
            - "8081:8080"
    server_b: 
        build: ./environment/user_server_b
        ports:
            - "8082:8080"
    service:
        build: ./solutions/${SOLUTION_LANG}
        ports:
            - "8080:8080"
        environment:
            - SERVICE_A_HOST=server_a:8080
            - SERVICE_B_HOST=server_b:8080
            - DB_HOST=db
        depends_on:
            - "db"
            - "server_a"
            - "server_b"
    load-test:
        image: locustio/locust
        ports:
            - "8089:8089"
        volumes:
            - ${PWD}/loadtest/:/mnt/locust
        depends_on:
            - "service"
        command: ["-f", "/mnt/locust/locustfile.py", "--config", "/mnt/locust/loadtest.conf", "--html", "/mnt/locust/${SOLUTION_LANG}_result.html"]