version: "3.9"  # optional since v1.27.0
services:
    db:
        build: ./company_db
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=pass